Capistrano::Configuration.instance(:must_exist).load do

  _cset(:emails_to_notify) { [] }

  namespace :deploy do
    namespace :send_notifications do
      desc <<-DESC
        Send notifications about deploy.
        Get emails from :emails_to_notify
      DESC
      task :email do
        unless emails_to_notify.empty?
          notification_message = <<-MESSAGE
            This email was generated by Capistrano before delivery.

            -------------------------------------------------------
            Current deploy Branch: #{branch.strip}
            Current deploy Revision: #{revision.strip}

            Previous deploy Revision: #{previous_revision.strip}
            -------------------------------------------------------

            See this commit on Github: #{repository.sub(':', '/').sub('git@', 'https://').sub('.git', "/commit/#{revision.strip}")}
            See changelist on Github: #{repository.sub(':', '/').sub('git@', 'https://').sub('.git', "/compare/#{previous_revision}...#{revision.strip}")}
          MESSAGE

          run_locally %(echo "#{notification_message}" | mail -s "#{application} delivery by #{user}" '#{emails_to_notify.join("' '")}')
        end
      end
    end
  end
end
